# Alembic configuration file.
# the '[alembic]' section of this file is read by the generated
# alembic revision scripts.

[alembic]
# path to migration files
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# as a comma-separated list of paths. e.g. on a unix/windows system
# could look like: ./src:./vendor/includes or on windows a system could look
# like: .\src;.\vendor\includes
# <%text><%\endtext>
#
# %Environment variable ${EnvironmentVariableName} is expanded by the operating system:
# Unix, Windows: ${PYTHONPATH}
# %Windows only: ${ALEMBIC_INI_DIR} is expanded by Alembic to the directory
# containing this file
pythonpath = .

# prepend the specified paths to sys.path before importing
# the application module. Defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the `datetime.tz` module from the standard library
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in "revision" files
# compared to the length of "down_revision" it's shorter.
# %default value is determined by the length of the above "version_path_pattern"
# string  and the character set of `revision_characters` below
# mako line length correspond to how Line lenght the fil gets mirrored into character set
# note: for SqLite characters in DDl is not so important.
# max_identifier_length = 63

# The SQL compiler to use when rendering the schemas
# The default value is selected based on the current database being used
# sqlalchemy_url location of the database.  Migration scripts
# will use this `sqlalchemy.url` in the 'sqlalchemy.url' section
# of the .alembic.ini file as the source of the target database.
# If you have multiple databases and you want to use migrations
# for multiple of them, configure their sqlalchemy urls
# under the [sqlalchemy.url] section.
sqlalchemy.url = sqlite:///./library.db


# [loggers]
# keys = root,sqlalchemy,alembic
#
# [handlers]
# keys = console
#
# [formatters]
# keys = generic
#
# [logger_root]
# level = WARN
# handlers = console
# qualname =
#
# [logger_sqlalchemy]
# level = WARN
# handlers =
# qualname = sqlalchemy.engine
#
# [logger_alembic]
# level = INFO
# handlers =
# qualname = alembic
#
# [handler_console]
# class = StreamHandler
# args = (sys.stderr,)
# level = NOTSET
# format = %(levelname)s:%(name)s:%(message)s
#
# [formatter_generic]
# format = %(levelname)s:%(asctime)s:%(name)s:%(message)s
# datefmt = %H:%M:%S
